import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { ApolloClientProvider, client } from '../client/ApolloClientProvider';

const pretendard = localFont({
  src: '../../public/fonts/PretendardVariable.woff2',
  weight: '100 900',
  display: 'swap',
  variable: '--font-pretendard',
  fallback: ['system-ui', 'sans-serif'],
});

export const metadata: Metadata = {
  title: 'Scheduler',
  description: 'Generated by create next app',
};

// 모든 언어에 Pretendard를 기본 폰트로 사용
const fontFamily = 'var(--font-pretendard), sans-serif';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`antialiased flex flex-col min-h-screen overflow-x-hidden ${pretendard.variable}`}
        style={{ fontFamily }}
      >
        <ApolloClientProvider client={client}>{children}</ApolloClientProvider>
      </body>
    </html>
  );
}
