import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { ApolloClientProvider, client } from '../client/ApolloClientProvider';
import SessionProviderWrapper from '../components/SessionProviderWrapper';
import ScheduleProviderWrapper from '../components/ScheduleProviderWrapper';
import type { Schedule } from '../types/schedule';

const pretendard = localFont({
  src: '../../public/fonts/PretendardVariable.woff2',
  weight: '100 900',
  display: 'swap',
  variable: '--font-pretendard',
  fallback: ['system-ui', 'sans-serif'],
});

export const metadata: Metadata = {
  title: 'Scheduler',
  description: 'Generated by create next app',
  icons: {
    icon: '/images/icons/alarm.png',
  },
};

// 모든 언어에 Pretendard를 기본 폰트로 사용
const fontFamily = 'var(--font-pretendard), sans-serif';

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // 초기 데이터는 빈 배열로 설정하고, 클라이언트에서 useQuery로 가져옴
  const schedules: Schedule[] = [];

  return (
    <html lang='en'>
      <body
        className={`antialiased flex flex-col min-h-screen overflow-x-hidden ${pretendard.variable}`}
        style={{ fontFamily }}
      >
        <SessionProviderWrapper>
          <ApolloClientProvider client={client}>
            <ScheduleProviderWrapper initialSchedules={schedules}>
        {children}
            </ScheduleProviderWrapper>
          </ApolloClientProvider>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
